apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: ecommerce
  POSTGRES_PASSWORD: changeme-strong-password
  POSTGRES_DB: shop
